### ISSUE TITLE
Does not work on the server

### ISSUE THREAD

**Issue by gemsvertus** [anviaan/Chiseled-Bookshelf-Visualizer-1.20#1]
I am faced with the problem that the mod does not work on different servers, should it work on servers at all? The description didn't say! If it should not work on servers, then please make the mod work...

**Comment by Mikkel136** [comment]
Can confirm on PaperMC and PurpurMC 1.20.2 and 1.20.4 (unstable builds)

**Comment by SoulxluoS** [comment]
This will only work on a Fabric/Quilt server with the mod installed & client installed
