### ISSUE TITLE
The game crashes when starting in version 1.20.5 & 1.20.6

### ISSUE THREAD

**Issue by J4PC** [anviaan/Chiseled-Bookshelf-Visualizer-1.20#3]
![image](https://github.com/anviaan/Chiseled-Bookshelf-Visualizer/assets/97805057/491094a8-7eb4-4f45-958a-c12b3bd971b0)

> The game crashed whilst bootstrap
> Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_7714 failed

farbic-loader-0.15.10-1.20.5 **using the mods:**
- (Fabric)Chiseled-Bookshelf-Visualizer-1.20-2.0
- fabric-api-0.97.6+1.20.5

**Comment by ReneMuetti** [comment]
I really hope that the MOD is not dead and that there will be an update to the current version.

**Comment by ReneMuetti** [comment]
Hello
It would be really great if the MOD is ported to MC version 1.20.6 and to version 1.21.
It's really tedious to manage the bridge in the shelves. In the meantime, I no longer have an overview of which bridgeers are available and which may have been stored where.

Many Thx

**Comment by anviaan** [comment]
It will not be available for version 1.20.6, but it will be ported to 1.21 and 1.21.1.
