### ISSUE TITLE
Copy of my mod.

### ISSUE THREAD

**Issue by lukasabbe** [anviaan/Chiseled-Bookshelf-Visualizer-1.20#5]
Hey I know my mod is under MIT. That's for a reason I have it as that. I want people to learn from what I write and take the parts that you want, and built upon them. Without being afraid of someone coming and being angry about it. I am even for reuploading projects, I am personally not going to be angry if anyone reuploads my projects to Curseforge for example. I don't do it and I won't do it.

If I stop coding iI want people to be able to update my mods without contacting me. 

But now you have taken my code without credit and uploaded it to Modrinth. As the bigger mod you are going to get more of the downloads. 

It would be awesome if you credited my mod minimum or just don't reupload it like now.

//Lukas, PS, its fun that you like my code :)

**Comment by anviaan** [comment]
First of all I want to apologize if I caused you any inconvenience. On the other hand, in the fabric.mod.json file I had placed you as the author of the mod, and according to the MIT license I copied your license and placed it, but what I noticed is that the license did not have your name at that time, but I copied it as is.
To have it clearer I have updated the license to the current one (with the name included) and I have created a new repository where it is a frok of your repository, also in the README and in the description of Modrinth, it will be put textually that this project is a fork of yours and adding a link to this one.

**Comment by lukasabbe** [comment]
Sure sure, that's better. For me that still breaks Modrinths rules about uploading the same project. It's the same! you have only added one feature. 

Do I think that if I upload for example like FerriteCore on Modrinth again with the right acknowledgments, and the only feature i add is that i can turn off and on the mod. Is that okay? I don't think so, but maybe Modrinth thinks so, and if it's okay for there standards i am okay with it.

I don't know how much time you have had in ur personal life, but think it's funny that you only say anything in this issue when the project gets taken down. It has been a week

After a lot of thinking, the problem for me is not the copying of the mod, it's not that you did not place my name anywhere beside one place (pretty hidden one). It is that you did this when I had an active mod (newly released) and you had 16k downloads on an existing project. The only thing that would do is killlng my mod because you have bigger mod. You did not contact me before doing this and even after you don't even answer my issue until ur project gets taken down. It's not about licenses, this is abusing licenses. Please read what I think about MIT in my first message, that still stands.

Many other mod authors when they don't want to update their mod do link to a new mod. That's what you should have done. 

Please think about this.
